import "./globals.css";

export const metadata = {
  title: "CTH-CONTROLS Login in dev-test",
  description:
    "Generated by create next app. Demonstrates the functionality of a login form. The login form has client side validation to show the user if the email is valid, and if not valid, add the applicable styles and error message to the user",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
