import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout =({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <div className={inter.className}>
      {children}
    </div>
  )
}

export default RootLayout